export const ROUTES = {
  home: '/',
  login: '/login',
  account: '/account',
  register: '/register',
  beers: '/beers',
  cart: '/cart',
  productPage: '/product/:productId',
  faq: '/',
  about: '/about',
  contact: '/',
  delivery: '/',
  accessibility: '/',
  privacy: '/',
  terms: '/',
  cookie: '/',
  responsibility: '/',
  facebook: '/',
  instagram: '/',
  x: '/',
} as const;
